title: Let's survive automation
description: > # this means to ignore newlines until "permalink:"
  Automation tips, selenium tips, 
  resolving common config problems, discussing new patterns, 
  investigating AI for selenium, DevOps in automation live.
permalink: ':title'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://borjarobles.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Borja Robles # add your name
author-img: logo.png # add your photo
about-author: Selenium survivor, always hungry to keep learning

rename: QA LEMMINGS
reabout: >
  Investigating new tips about automation factors,
  discussing new patterns


social-github: borjarobles # add your Github handle
social-email: borja.robles@gmail.com

# Disqus
discus-identifier: qa-lemmings # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
